[workspace]
resolver = '2'
package.authors = ["zrothschild"]
members = [
    "pancakes",
    "vec_macro_rules",
    "hello_macro",
    "hello_macro_derive",
    "hello_macro_attribute",

]
default-members = ["hello_macro_fn"]
